import type { Ticket } from "./types";

export const initialTickets: Ticket[] = [
  {
    id: "TSK-482",
    title: "Согласовать сценарий onboarding для новых клиентов",
    project: "Product design",
    status: "in_progress",
    priority: "high",
    labels: ["UX", "Клиенты"],
    assignee: { name: "Мадина Ахметова", initials: "МА" },
    dueAt: "2026-07-08",
    comments: 6,
  },
  {
    id: "TSK-476",
    title: "Подготовить API-контракт для центра уведомлений",
    project: "Core platform",
    status: "review",
    priority: "urgent",
    labels: ["Backend", "API"],
    assignee: { name: "Илья Носов", initials: "ИН" },
    dueAt: "2026-07-07",
    comments: 3,
  },
  {
    id: "TSK-469",
    title: "Проверить доступы к новому рабочему пространству",
    project: "Operations",
    status: "backlog",
    priority: "medium",
    labels: ["Security"],
    assignee: { name: "Алина Миронова", initials: "АМ" },
    dueAt: "2026-07-11",
    comments: 1,
  },
  {
    id: "TSK-462",
    title: "Собрать обратную связь после релиза 2.4",
    project: "Product design",
    status: "done",
    priority: "low",
    labels: ["Research"],
    assignee: { name: "Денис Орлов", initials: "ДО" },
    dueAt: "2026-07-04",
    comments: 8,
  },
  {
    id: "TSK-451",
    title: "Настроить статусы SLA для запросов поддержки",
    project: "Customer success",
    status: "in_progress",
    priority: "high",
    labels: ["SLA", "Support"],
    assignee: { name: "София Ким", initials: "СК" },
    dueAt: "2026-07-09",
    comments: 4,
  },
];
